remove sinon sandbox usage
testjavascript/nodejs-integration-tests-best-practices pull request #41
Opened 2020-12-29 16:00 UTC by DanielGluskin

issue #28

2021-01-03 19:14 UTC, goldbergyoni requested changes
@DanielGluskin This is a great fix.

One important clarification - sinon.restore should exist in beforeEach, otherwise nothing will clean the modifications that test1 is doing and test3 will not be aware of those changes. Sinon has no way to know when a test ends and clean-up. Previously one had to create a sandbox and maintain as global var, now this can be done directly over the sinon object

Try it yourself (you're on your way to be a testing expert:)), make a test stub the 'addOrder' to throw error, see that the next tests also fail.

2021-01-11 17:06 UTC, mikicho requested changes
much cleaner!

2021-01-11 17:06 UTC, mikicho commented on example-application/test/basic-tests.test.js
> +  sinon.restore();
IMO this should be in `afterEach`
1. More reasonable.
2. Sometimes you may want to declare some stubs in the `beforeEach` and the restore will remove them

2021-01-11 17:06 UTC, mikicho commented on various-receipes/authentication/test/auth-example-with-stub.test.js
> +    sinon.restore();
> Sometimes you may want to declare some stubs in the beforeEach and the restore will remove them

for example... 😅

2021-01-17 21:03 UTC, closed without merging

2021-01-17 23:01 UTC, mikicho commented
@DanielGluskin why?

2021-01-18 08:50 UTC, DanielGluskin commented
@mikicho was fixed and merged by an other PR.