edit readme
testjavascript/nodejs-integration-tests-best-practices pull request #96
Opened 2021-07-11 15:32 UTC by DanielGluskin

- edit bullets 1, 2, 3 & 6. (4 & 5 are labeled as draft).

2021-07-11 17:05 UTC, goldbergyoni requested changes
See comments

2021-07-11 17:05 UTC, goldbergyoni commented on README.md
> +  await dockerCompose.upAll();
That's mystery - How come we can invoke dockerCompose liks this?

Put more context, require the relevant package, give a bit more context

2021-07-11 17:05 UTC, goldbergyoni commented on README.md
> +  if (isCI) {
Give more context - Put comments above, "//global-teardown.js - Where we clean-up after all tests", show jest config like you did before

2021-07-11 17:05 UTC, goldbergyoni commented on README.md
> +  await npmCommandAsPromise(['db:migrate']);
The reader won't understand where is this coming from, don't count on reading everything before. Give more context.

Put jest config, put comment above "// In the global setup we also install all the tables"

2021-07-14 09:28 UTC, DanielGluskin commented
@goldbergyoni

2021-07-14 17:13 UTC, goldbergyoni commented
@DanielGluskin Tests fail, can't merge

2021-07-14 20:46 UTC, DanielGluskin commented
> @DanielGluskin Tests fail, can't merge

@goldbergyoni they fail with the target branch - not related to my PR. I'll try to fix that tomorrow.

2021-07-21 13:20 UTC, goldbergyoni approved these changes

2021-07-21 13:20 UTC, merged